language: ruby
env:
  - "DB=postgresql"
before_script:
  - "cp ./config/database.yml.travis ./config/database.yml"
  - "bundle exec rake db:setup"
rvm:
  - 2.2.0
script:
  - "bundle exec rake spec"
  - "bundle exec rake spec:javascript"
